# Generated by Django 3.2.5 on 2021-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('number_of_instaces', models.IntegerField()),
                ('start_test_at', models.DateTimeField()),
                ('instances', models.ManyToManyField(to='mazebolt_project.Instance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
