# Generated by Django 3.2.5 on 2021-07-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazebolt_project', '0003_auto_20210724_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number_of_instaces',
        ),
    ]
